### PR TITLE
TRITON-2169 CMON should gzip encode responses

### PR DESCRIPTION
**Pull request by bahamat**

### CODE REVIEW

**Review by twhiteman — COMMENTED** [review]
Looks good, but please bump the package.json version.

**Comment by bahamat** [comment]
Ah, yeah. I always forget about that. We're at 1.7.0 now, should we go 1.7.1 or 1.8?

**Comment by twhiteman** [comment]
1.8 sounds good

**Comment by bahamat** [comment]
1.8 it is. Done.

**Review by twhiteman — DISMISSED** [review]

**Review by twhiteman — APPROVED** [review]

**Pull request merged**
